### ISSUE TITLE
ported to current MIRTK

### ISSUE THREAD

**Issue by jcupitt** [MIRTK/Viewer#1]
Hello, I have a branch here:

https://github.com/jcupitt/Viewer/tree/switch-to-mirtk

which builds cleanly against current MIRTK. It seems to work, though I've not tested it much.

**Comment by schuhschuh** [comment]
Awesome! You could send a PR, as the current `master` code is kind of useless in the public domain...

**Comment by jcupitt** [comment]
OK, I'll get it to at least load and display a volume, then make a PR.

**Comment by schuhschuh** [comment]
Sorry I just got back to this. The PR's are now merged.
